# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Railor Blog
tagline:             'Where thoughts become writing.'
description:         'This is my blog where I share code ideas and (maybe) tutorials. It is also a way for me to connect with readers through writing.'
url:                 'http://www.railor-blog.me'
baseurl:             'http://www.railor-blog.me'
paginate:            5

# About/contact
author:
  name:              Landon Gravat
  url:               https://twitter.com/mdo
  email:             railinator4903@gmail.com

# Custom vars
version:             1.0.0

twitter: Railor_Music
facebook: RailorMusic
snapchat: railrunner166
dribbble: RailRunner16
gplus: 
behance: railinator483c
